# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "Continuous Integration"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_ROOT_VERSION: "1.99.99"

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.2"
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
        composer-deps:
          - "lowest"
          - "highest"

    steps:
      - name: "Configure Git (for Windows)"
        if: ${{ matrix.os == 'windows-latest' }}
        shell: "bash"
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: "Checkout repository"
        uses: "actions/checkout@v3.6.0"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.25.1"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "none"

      - name: "Install dependencies (Composer)"
        run: "composer install"

      - name: "Run unit tests (PHPUnit)"
        run: "php vendor/bin/phpunit tests/"
